# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[container]
disabled=true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](green)"
error_symbol = "[➜](red)"
vicmd_symbol = "[❮](green)"

[directory]
truncation_length = 4
# Catppuccin 'lavender'
style = "bold blue"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
